# Generated by Django 4.1.6 on 2023-02-18 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advertisement',
            old_name='author_id',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='advertisement',
            old_name='category_id',
            new_name='category',
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
